// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace RussianNationalMessengerServer.Models;

public partial class ChatMember
{
    [JsonPropertyName("chatId")]
    public Guid ChatId { get; set; }

    [JsonPropertyName("username")]
    public string Username { get; set; }

    [JsonPropertyName("joinedAt")]
    public DateTime JoinedAt { get; set; }

    [JsonIgnore]
    public virtual Chat Chat { get; set; }

    [JsonIgnore]
    public virtual User UsernameNavigation { get; set; }
}